/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2015-11-27 at 16:39:17 UTC 
 * Modify at your own risk.
 */

package com.appspot.thoughtsapp_1141.thoughts;

/**
 * Service definition for Thoughts (v4).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ThoughtsRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Thoughts extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the thoughts library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://thoughtsapp-1141.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "thoughts/v4/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Thoughts(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Thoughts(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getThought".
   *
   * This request holds the parameters needed by the thoughts server.  After setting any optional
   * parameters, call the {@link GetThought#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetThought getThought() throws java.io.IOException {
    GetThought result = new GetThought();
    initialize(result);
    return result;
  }

  public class GetThought extends ThoughtsRequest<com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought> {

    private static final String REST_PATH = "getThought";

    /**
     * Create a request for the method "getThought".
     *
     * This request holds the parameters needed by the the thoughts server.  After setting any
     * optional parameters, call the {@link GetThought#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetThought#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetThought() {
      super(Thoughts.this, "GET", REST_PATH, null, com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetThought setAlt(java.lang.String alt) {
      return (GetThought) super.setAlt(alt);
    }

    @Override
    public GetThought setFields(java.lang.String fields) {
      return (GetThought) super.setFields(fields);
    }

    @Override
    public GetThought setKey(java.lang.String key) {
      return (GetThought) super.setKey(key);
    }

    @Override
    public GetThought setOauthToken(java.lang.String oauthToken) {
      return (GetThought) super.setOauthToken(oauthToken);
    }

    @Override
    public GetThought setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetThought) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetThought setQuotaUser(java.lang.String quotaUser) {
      return (GetThought) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetThought setUserIp(java.lang.String userIp) {
      return (GetThought) super.setUserIp(userIp);
    }

    @Override
    public GetThought set(String parameterName, Object value) {
      return (GetThought) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "put".
   *
   * This request holds the parameters needed by the thoughts server.  After setting any optional
   * parameters, call the {@link Put#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought}
   * @return the request
   */
  public Put put(com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought content) throws java.io.IOException {
    Put result = new Put(content);
    initialize(result);
    return result;
  }

  public class Put extends ThoughtsRequest<com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought> {

    private static final String REST_PATH = "putThought";

    /**
     * Create a request for the method "put".
     *
     * This request holds the parameters needed by the the thoughts server.  After setting any
     * optional parameters, call the {@link Put#execute()} method to invoke the remote operation. <p>
     * {@link Put#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought}
     * @since 1.13
     */
    protected Put(com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought content) {
      super(Thoughts.this, "POST", REST_PATH, content, com.appspot.thoughtsapp_1141.thoughts.model.ThoughtsIOThought.class);
    }

    @Override
    public Put setAlt(java.lang.String alt) {
      return (Put) super.setAlt(alt);
    }

    @Override
    public Put setFields(java.lang.String fields) {
      return (Put) super.setFields(fields);
    }

    @Override
    public Put setKey(java.lang.String key) {
      return (Put) super.setKey(key);
    }

    @Override
    public Put setOauthToken(java.lang.String oauthToken) {
      return (Put) super.setOauthToken(oauthToken);
    }

    @Override
    public Put setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Put) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Put setQuotaUser(java.lang.String quotaUser) {
      return (Put) super.setQuotaUser(quotaUser);
    }

    @Override
    public Put setUserIp(java.lang.String userIp) {
      return (Put) super.setUserIp(userIp);
    }

    @Override
    public Put set(String parameterName, Object value) {
      return (Put) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Thoughts}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Thoughts}. */
    @Override
    public Thoughts build() {
      return new Thoughts(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ThoughtsRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setThoughtsRequestInitializer(
        ThoughtsRequestInitializer thoughtsRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(thoughtsRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
